name: Setup GStreamer
description: Install GStreamer development libraries

runs:
  using: composite
  steps:
    - name: Install GStreamer (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

    - name: Install GStreamer (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: brew install gstreamer

    - name: Install GStreamer (Windows)
      if: runner.os == 'Windows'
      uses: blinemedical/setup-gstreamer@v1
